### ISSUE TITLE
Invalid URI when calling base64.encode

### ISSUE THREAD

**Issue by aranhahb** [riyadhalnur/node-base64-image#27]
* node version: v6.10.2
* npm version: 3.10.10

### Error output
```
 Error: Invalid URI "//cdn.macrumors.com/article-new/2016/01/iOS-9-Siri-250x213.jpg?retina"
    at Request.init (C:\Users\acer\OneDrive\Projects\newsfeed\node_modules\node-base64-image\node_modules\request\request.js:275:31)
    at new Request (C:\Users\acer\OneDrive\Projects\newsfeed\node_modules\node-base64-image\node_modules\request\request.js:129:8)
    at request (C:\Users\acer\OneDrive\Projects\newsfeed\node_modules\node-base64-image\node_modules\request\index.js:55:10)
    at Object.encode (C:\Users\acer\OneDrive\Projects\newsfeed\node_modules\node-base64-image\dist\node-base64-image.js:63:27)
    at Promise (C:\Users\acer\OneDrive\Projects\newsfeed\lib\post.js:48:14)
    at tryCallTwo (C:\Users\acer\OneDrive\Projects\newsfeed\node_modules\promise\lib\core.js:45:5)
    at doResolve (C:\Users\acer\OneDrive\Projects\newsfeed\node_modules\promise\lib\core.js:200:13)
    at new Promise (C:\Users\acer\OneDrive\Projects\newsfeed\node_modules\promise\lib\core.js:66:3)
    at share (C:\Users\acer\OneDrive\Projects\newsfeed\lib\post.js:45:12)
    at Timeout._onTimeout (C:\Users\acer\OneDrive\Projects\newsfeed\share-test.js:45:18)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

### More details
Error thrown when callin base64.encode passing an URI containing upper cases letters

**Comment by riyadhalnur** [comment]
You need to pass in the protocol when passing in a URL you want to encode, i.e. `https://cdn.macrumors.com/article-new/2016/01/iOS-9-Siri-250x213.jpg?retina`

**Comment by aranhahb** [comment]
What you mean by "pass in the protocol" ?

**Comment by riyadhalnur** [comment]
The `http` or `https` in front of the URL is the protocol that the browser connects over with the server. The `encode` function expects a fully formed valid URL. The URL you want to use needs to be - `https://cdn.macrumors.com/article-new/2016/01/iOS-9-Siri-250x213.jpg?retina` - in order to work.

**Comment by aranhahb** [comment]
Many thanks riyadhalnur!
